/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDevice: typeof import('./src/components/AddDevice.vue')['default']
    AddDeviceDialog: typeof import('./src/components/AddDeviceDialog.vue')['default']
    AddHome: typeof import('./src/components/AddHome.vue')['default']
    AppHeader: typeof import('./src/components/home/Header.vue/index.js')['default']
    AppList: typeof import('./src/components/home/AppList.vue')['default']
    copy: typeof import('./src/components/AddDevice copy.vue')['default']
    DeviceSelector: typeof import('./src/components/home/DeviceSelector.vue')['default']
    DrButton: typeof import('./src/components/DrButton.vue')['default']
    Header: typeof import('./src/components/home/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home/index.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PageHome: typeof import('./src/components/PageHome.vue')['default']
    ScrollAreaRoot: typeof import('reka-ui')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('reka-ui')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('reka-ui')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('reka-ui')['ScrollAreaViewport']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TooltipArrow: typeof import('reka-ui')['TooltipArrow']
    TooltipContent: typeof import('reka-ui')['TooltipContent']
    TooltipPortal: typeof import('reka-ui')['TooltipPortal']
    TooltipProvider: typeof import('reka-ui')['TooltipProvider']
    TooltipRoot: typeof import('reka-ui')['TooltipRoot']
    TooltipTrigger: typeof import('reka-ui')['TooltipTrigger']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
