/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDevice: typeof import('./src/components/AddDevice.vue')['default']
    AddDeviceDialog: typeof import('./src/components/AddDeviceDialog.vue')['default']
    AppInfoDialog: typeof import('./src/components/AppInfoDialog.vue')['default']
    AppList: typeof import('./src/components/home/AppList.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ContextMenuContent: typeof import('reka-ui')['ContextMenuContent']
    ContextMenuItem: typeof import('reka-ui')['ContextMenuItem']
    ContextMenuPortal: typeof import('reka-ui')['ContextMenuPortal']
    ContextMenuRoot: typeof import('reka-ui')['ContextMenuRoot']
    ContextMenuSeparator: typeof import('reka-ui')['ContextMenuSeparator']
    ContextMenuTrigger: typeof import('reka-ui')['ContextMenuTrigger']
    DialogContent: typeof import('reka-ui')['DialogContent']
    DialogDescription: typeof import('reka-ui')['DialogDescription']
    DialogOverlay: typeof import('reka-ui')['DialogOverlay']
    DialogPortal: typeof import('reka-ui')['DialogPortal']
    DialogRoot: typeof import('reka-ui')['DialogRoot']
    DialogTitle: typeof import('reka-ui')['DialogTitle']
    Home: typeof import('./src/components/home/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ScrollAreaRoot: typeof import('reka-ui')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('reka-ui')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('reka-ui')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('reka-ui')['ScrollAreaViewport']
    Settings: typeof import('./src/components/Settings.vue')['default']
    TooltipContent: typeof import('reka-ui')['TooltipContent']
    TooltipPortal: typeof import('reka-ui')['TooltipPortal']
    TooltipProvider: typeof import('reka-ui')['TooltipProvider']
    TooltipRoot: typeof import('reka-ui')['TooltipRoot']
    TooltipTrigger: typeof import('reka-ui')['TooltipTrigger']
  }
}
